### ISSUE TITLE
[Android] SQLiteConstraintException devtodev 3.5.0 unity 2020.3.38f1

### ISSUE THREAD

**Issue by SuperUnityCoder** [devtodev-analytics/Unity-sdk-3.0#7]
DevToDev version: 3.5.0
Unity version: 2020.3.38f1
Device: Motorola One
OS: Android 10

Hi, our app after restart crashes with exception:
FATAL EXCEPTION: pool-40-thread-1
android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: users.projectId, users.userId (code 2067 SQLITE_CONSTRAINT_UNIQUE)
at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:831)
at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:756)
at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:66)
at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1704)
at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1650)
at com.devtodev.analytics.internal.storage.SQLiteProvider.update(SQLiteProvider.kt:119)
at com.devtodev.analytics.internal.storage.Repository.update(Repository.kt:1)
at com.devtodev.analytics.internal.managers.CoreManager.checkUnityUserId(CoreManager.kt:132)
at com.devtodev.analytics.internal.managers.StateManager.<init>(StateManager.kt:24)
at com.devtodev.analytics.internal.core.Core$a.invoke(Core.kt:38)
at com.devtodev.analytics.internal.queue.QueueManager$Companion.d(QueueManager.kt:1)
at com.devtodev.analytics.internal.queue.-$$Lambda$ZAjvo-fi54tKNKnlwmGwSbmlW8g.run(Unknown Source:2)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)

**Comment by kaikristo** [comment]
Yeah, we found this problem. We will include the fix in the next release

**Comment by SuperUnityCoder** [comment]
Hello, is there any ETA for the next release?

**Comment by kaikristo** [comment]
@SuperUnityCoder Hello, ETA is end of the next week

**Comment by kaikristo** [comment]
Fixed in 3.6.0 version
